server:
  port: 8080
  servlet:
    context-path: /cdw

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=CONVERT_TO_NULL"
    username: root
    password: root
  jpa:
    sql:
      init:
        mode: always
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  jwt:
    signerKey: "4FDBF922FD266D8A6C1D7C5DA0989ED7"