server:
  port: 8080
  servlet:
    context-path: /cdw

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cdw_database?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  messages:
    encoding: UTF-8

  jwt:
    signerKey: "4FDBF922FD266D8A6C1D7C5DA0989ED7"
