vnpay:
  tmnCode: SO08KM91
  hashSecret: 4307HNUTL9JFMNXN3MPGLSHAR31XZO6W
  paymentUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:3000/payment-result


server:
  port: 8080
  servlet:
    context-path: /cdw

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cdw_database?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true


  messages:
    encoding: UTF-8
    basename: messages,messages_vi,messages_en

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
          google:
            client-id: 1064124095561-rritsm1pbm2vnt29mocdb1n5pvuen0a8.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/cdw/login/oauth2/code/google
            scope:
              - email
              - profile
  jwt:
    signerKey: "4FDBF922FD266D8A6C1D7C5DA0989ED7"
  mail:
    host: smtp.gmail.com
    port: 587
    username: phuonghuynh131415@gmail.com
    password: iefb fnla vpna vkob
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
    default-encoding: UTF-8
app:
  frontend:
    url: http://localhost:3000
  jwt:
    password-reset:
      secret: "4FDBF922FD266D8A6C1D7C5DA0989ED7"
      expiration: 3600000